/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAL_H_RPCGEN
#define _CAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct two_in {
	int a;
	int b;
};
typedef struct two_in two_in;

#define CAL 0x20fff100
#define ASSI_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDITION 1
extern  int * addition_1(struct two_in *, CLIENT *);
extern  int * addition_1_svc(struct two_in *, struct svc_req *);
#define SUBTRACTION 2
extern  int * subtraction_1(struct two_in *, CLIENT *);
extern  int * subtraction_1_svc(struct two_in *, struct svc_req *);
#define MULTIPLICATION 3
extern  int * multiplication_1(struct two_in *, CLIENT *);
extern  int * multiplication_1_svc(struct two_in *, struct svc_req *);
#define DIVISION 4
extern  int * division_1(struct two_in *, CLIENT *);
extern  int * division_1_svc(struct two_in *, struct svc_req *);
extern int cal_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDITION 1
extern  int * addition_1();
extern  int * addition_1_svc();
#define SUBTRACTION 2
extern  int * subtraction_1();
extern  int * subtraction_1_svc();
#define MULTIPLICATION 3
extern  int * multiplication_1();
extern  int * multiplication_1_svc();
#define DIVISION 4
extern  int * division_1();
extern  int * division_1_svc();
extern int cal_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_two_in (XDR *, two_in*);

#else /* K&R C */
extern bool_t xdr_two_in ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CAL_H_RPCGEN */
