/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"

int *
addition_1_svc(struct two_in *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a + argp->b;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
subtraction_1_svc(struct two_in *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a - argp->b;
	/*
	 * insert server code here
	 */

	return &result;
}

int *
multiplication_1_svc(struct two_in *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a * argp->b;
	/*
	 * insert server code here
	 */

	return &result;
}

int *
division_1_svc(struct two_in *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a / argp->b;
	/*
	 * insert server code here
	 */

	return &result;
}
